### ISSUE TITLE
composer requirements failing

### ISSUE THREAD

**Issue by OlliM** [valiton/SaferpayBundle#1]
I got this problem, when I tried to install your bundle:

payment/saferpay 3.0.2 requires payment/httpclient-implementation ~1.0 -> no matching package found.
    - payment/saferpay 3.0.1 requires payment/httpclient-implementation ~1.0 -> no matching package found.
    - payment/saferpay 3.0.0 requires payment/httpclient-implementation ~1.1,>=1.0 -> no matching package found.
    - valiton/saferpay-bundle dev-master requires payment/saferpay 3.0.\* -> satisfiable by payment/saferpay[3.0.0, 3.0.1, 3.0.2].
    - Installation request for valiton/saferpay-bundle dev-master -> satisfiable by valiton/saferpay-bundle[dev-master].

I've browsed the repos here https://github.com/payment, but I couldn't find a solution for this missing package...

Any ideas?

**Comment by uwej711** [comment]
You also have to install/require either payment/httpclient-buzz or payment/httpclient-guzzle. Both provide payment/httpclient-implementation
