### ISSUE TITLE
support Symfony 2.6

### ISSUE THREAD

**Issue by OlliM** [valiton/SaferpayBundle#2]
It would be nice if your package would work with Symfony 2.6.

What are the main reasons, it can't be supported yet? 
Anything I can do from my end?

Cheers

**Comment by uwej711** [comment]
Well, somebody just needs to try it and update the composer dependency to something <3.0

PR welcome

**Comment by OlliM** [comment]
Okay, so I'll test and let you know... if changes are needed, I'll prepare a PR

**Comment by uwej711** [comment]
fixed by #3
